[package]
name = "influxdb_iox"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"
default-run = "influxdb_iox"
readme = "README.md"

[workspace] # In alphabetical order
members = [
    "arrow_util",
    "data_types",
    "datafusion",
    "datafusion_util",
    "entry",
    "generated_types",
    "google_types",
    "influxdb2_client",
    "influxdb_iox_client",
    "influxdb_line_protocol",
    "influxdb_tsm",
    "ingest",
    "internal_types",
    "logfmt",
    "mem_qe",
    "mutable_buffer",
    "object_store",
    "observability_deps",
    "packers",
    "panic_logging",
    "query",
    "read_buffer",
    "server",
    "test_helpers",
    "tracker",
]

[profile.release]
debug = true

[profile.bench]
debug = true

[dependencies]
# Workspace dependencies, in alphabetical order
datafusion = { path = "datafusion" }
data_types = { path = "data_types" }
generated_types = { path = "generated_types" }
influxdb_iox_client = { path = "influxdb_iox_client", features = ["format"] }
influxdb_line_protocol = { path = "influxdb_line_protocol" }
influxdb_tsm = { path = "influxdb_tsm" }
internal_types = { path = "internal_types" }
ingest = { path = "ingest" }
logfmt = { path = "logfmt" }
mem_qe = { path = "mem_qe" }
metrics = { path = "metrics" }
mutable_buffer = { path = "mutable_buffer" }
num_cpus = "1.13.0"
object_store = { path = "object_store" }
observability_deps = { path = "observability_deps" }
packers = { path = "packers" }
panic_logging = { path = "panic_logging" }
query = { path = "query" }
read_buffer = { path = "read_buffer" }
server = { path = "server" }
tracker = { path = "tracker" }

# Crates.io dependencies, in alphabetical order
arrow = "4.0"
arrow-flight = "4.0"
byteorder = "1.3.4"
bytes = "1.0"
chrono = "0.4"
clap = "2.33.1"
csv = "1.1"
dirs = "3.0.1"
dotenv = "0.15.0"
flate2 = "1.0"
futures = "0.3"
http = "0.2.0"
hyper = "0.14"
once_cell = { version = "1.4.0", features = ["parking_lot"] }
opentelemetry-jaeger = { version = "0.12", features = ["tokio"] }
opentelemetry-otlp = "0.6"
parking_lot = "0.11.1"
itertools = "0.9.0"
parquet = "4.0"
# used by arrow/datafusion anyway
prettytable-rs = "0.8"
pprof = { version = "^0.4", default-features = false, features = ["flamegraph", "protobuf"] }
prost = "0.7"
# Forked to upgrade hyper and tokio
routerify = { git = "https://github.com/influxdata/routerify", rev = "274e250" }
rustyline = "8.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"
serde_urlencoded = "0.7.0"
snafu = "0.6.9"
structopt = "0.3.21"
thiserror = "1.0.23"
tikv-jemallocator = {version = "0.4.0", features = ["unprefixed_malloc_on_supported_platforms"] }
tikv-jemalloc-ctl = "0.4.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "parking_lot", "signal"] }
tokio-stream = { version = "0.1.2", features = ["net"] }
tokio-util = { version = "0.6.3" }
tonic = "0.4.0"
tonic-health = "0.3.0"
tonic-reflection = "0.1.0"
tracing-opentelemetry = { version = "0.12", default-features = false }

[dev-dependencies]
# Workspace dependencies, in alphabetical order
arrow_util = { path = "arrow_util" }
entry = { path = "entry" }
influxdb2_client = { path = "influxdb2_client" }
influxdb_iox_client = { path = "influxdb_iox_client", features = ["flight"] }
test_helpers = { path = "test_helpers" }
parking_lot = "0.11.1"

# Crates.io dependencies, in alphabetical order
assert_cmd = "1.0.0"
criterion = "0.3"
flate2 = "1.0"
hex = "0.4.2"
predicates = "1.0.4"
rand = "0.8.3"
reqwest = "0.11"
tempfile = "3.1.0"

[[bench]]
name = "encoders"
harness = false

[[bench]]
name = "line_parser"
harness = false

[[bench]]
name = "mapper"
harness = false

[[bench]]
name = "line_protocol_to_parquet"
harness = false

[[bench]]
name = "packers"
harness = false
