[package]
name = "influxdb_line_protocol"
version = "0.1.0"
authors = ["Paul Dix <paul@pauldix.net>"]
edition = "2018"

[dependencies] # In alphabetical order
nom = "5.1.1"
snafu = "0.6.2"
observability_deps = { path = "../observability_deps" }
ouroboros = "0.8.3"

[dev-dependencies] # In alphabetical order
criterion = "0.3.3"
test_helpers = { path = "../test_helpers" }
tikv-jemallocator = "0.4.0"

[[bench]]
name = "line_parser"
harness = false
